---
- name: Install ruby, rubygems, and development tools.
  yum:
    name: "{{ ruby_packages }}"
    state: present

- name: Add RepoForge repository
  yum:
    name: http://repository.it4i.cz/mirrors/repoforge/redhat/el7/en/x86_64/rpmforge/RPMS/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm
    state: present  
